//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MardisGeo.Data.@base
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ue_datos_tabla_
    {
        public int IdUE { get; set; }
        public string meta_instanceID { get; set; }
        public Nullable<double> Latitud { get; set; }
        public Nullable<double> Longitud { get; set; }
        public string Coordenadas { get; set; }
        public string Parroquia { get; set; }
        public string Zona { get; set; }
        public string Imagen { get; set; }
        public string Nombre { get; set; }
        public string Tamaño { get; set; }
        public string Tipo_Obra { get; set; }
        public string Categoria { get; set; }
        public string Esctructura { get; set; }
        public string Mamposteria { get; set; }
        public string Acabados { get; set; }
        public Nullable<double> Tamano_Obra { get; set; }
        public string Tipo_de_Cemento { get; set; }
        public Nullable<double> Cantidad_cemento { get; set; }
        public Nullable<double> Cemento_m3_por_ejecutar { get; set; }
        public string Tipo_mezcla { get; set; }
        public string Avance_Proyecto { get; set; }
        public Nullable<double> Porcentaje_Avance { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_finalizacion { get; set; }
        public string Responsable { get; set; }
        public string responsable2 { get; set; }
        public string Constructora { get; set; }
        public string marcas_cemento { get; set; }
        public string proveedor { get; set; }
        public string motivo_compra { get; set; }
        public string credito { get; set; }
        public Nullable<double> valor_m2 { get; set; }
        public string maposteria_otro { get; set; }
        public string acabados_otro { get; set; }
        public string hormigonera { get; set; }
        public string proveedor_otro { get; set; }
        public string otras_obras { get; set; }
        public string nombre_1 { get; set; }
        public string nombre_2 { get; set; }
        public string apellido_1 { get; set; }
        public string apellido_2 { get; set; }
        public string telefono { get; set; }
        public string celular { get; set; }
        public string Codigo { get; set; }
    }
}
