//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MardisGeo.Data.@base
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodigosDesactivados_Topsy
    {
        public int ID { get; set; }
        public string URI { get; set; }
        public string OBSERVACION { get; set; }
        public Nullable<System.DateTime> FECHA_DESACTIVACION { get; set; }
    }
}
