//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MardisGeo.Data.@base
{
    using System;
    using System.Collections.Generic;
    
    public partial class geo_dashboard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public geo_dashboard()
        {
            this.geo_map_profile = new HashSet<geo_map_profile>();
        }
    
        public int Id { get; set; }
        public string geo_dashboard_name { get; set; }
        public string geo_dashboard_descrip { get; set; }
        public string geo_dashboard_status { get; set; }
        public Nullable<System.DateTime> geo_dashboard_create_date { get; set; }
        public string geo_dashboard_usr { get; set; }
        public string geo_dashboard_link { get; set; }
        public string geo_dashboard_link_mobil { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<geo_map_profile> geo_map_profile { get; set; }
    }
}
