//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MardisGeo.Data.@base
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MardisGEOEntities : DbContext
    {
        public MardisGEOEntities()
            : base("name=MardisGEOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<geo_categoria> geo_categoria { get; set; }
        public virtual DbSet<geo_des_foto> geo_des_foto { get; set; }
        public virtual DbSet<geo_foto> geo_foto { get; set; }
        public virtual DbSet<geo_img_ubicacion> geo_img_ubicacion { get; set; }
        public virtual DbSet<geo_map> geo_map { get; set; }
        public virtual DbSet<geo_map_account> geo_map_account { get; set; }
        public virtual DbSet<geo_map_profile> geo_map_profile { get; set; }
        public virtual DbSet<geo_profile> geo_profile { get; set; }
        public virtual DbSet<geo_secuencial> geo_secuencial { get; set; }
        public virtual DbSet<geo_ubicacion> geo_ubicacion { get; set; }
        public virtual DbSet<geo_usr_profile> geo_usr_profile { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tpo_usr_geo> tpo_usr_geo { get; set; }
        public virtual DbSet<USER_GEO> USER_GEO { get; set; }
    }
}
