//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MardisGeo.Data.@base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Query
    {
        public System.DateTime C_URI { get; set; }
        public System.DateTime C_CREATOR_URI_USER { get; set; }
        public System.DateTime C_CREATION_DATE { get; set; }
        public Nullable<System.DateTime> C_LAST_UPDATE_URI_USER { get; set; }
        public System.DateTime C_LAST_UPDATE_DATE { get; set; }
        public Nullable<System.DateTime> C_TOP_LEVEL_AURI { get; set; }
        public byte[] VALUE { get; set; }
    }
}
