//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MardisGeo.Data.@base
{
    using System;
    using System.Collections.Generic;
    
    public partial class si_opc_apl
    {
        public int si_opc_apl_cod { get; set; }
        public Nullable<int> si__si_opc_apl_cod { get; set; }
        public string si_opc_apl_id { get; set; }
        public string si_opc_apl_nom_menu { get; set; }
        public string si_opc_apl_nom_ventana { get; set; }
        public string si_opc_apl_action { get; set; }
        public string si_opc_apl_controller { get; set; }
        public string si_opc_apl_glifos { get; set; }
        public string usr_hos_web { get; set; }
        public string usr_cmb_web { get; set; }
    }
}
