//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MardisGeo.Data.@base
{
    using System;
    using System.Collections.Generic;
    
    public partial class si_tpo_usuario
    {
        public int si_tpo_usr_cod { get; set; }
        public string si_tpo_usr_nom { get; set; }
        public string usr_hos_web { get; set; }
        public string usr_cmb_web { get; set; }
    }
}
